In [24]:
!pip install snowflake-connector-python
!pip install alpha_vantage

Requirement already satisfied: snowflake-connector-python in /usr/local/lib/python3.10/dist-packages (3.12.2)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (1.17.1)
Requirement already satisfied: cryptography>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (43.0.1)
Requirement already satisfied: pyOpenSSL<25.0.0,>=16.2.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (24.2.1)
Requirement already satisfied: pyjwt<3.0.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (2.9.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (2024.2)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (2.32.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (24.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (2024.8.30)
Requirement already satisfied: typing-extensions<5,>=4.3 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (4.12.2)
Requirement already satisfied: filelock<4,>=3.5 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (3.16.1)
Requirement already satisfied: sortedcontainers>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (4.3.6)
Requirement already satisfied: tomlkit in /usr/local/lib/python3.10/dist-packages (from snowflake-connector-python) (0.13.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python) (2.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0->snowflake-connector-python) (2.2.3)
Requirement already satisfied: alpha_vantage in /usr/local/lib/python3.10/dist-packages (3.0.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from alpha_vantage) (3.10.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from alpha_vantage) (2.32.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.11.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (2024.8.30)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from multidict<7.0,>=4.5->aiohttp->alpha_vantage) (4.12.2)

In [32]:
from google.colab import userdata
vantage_api_key = userdata.get('vantage_api_key')

In [33]:
symbol = "LMT"
# note that Formatted String Literal is used here
url = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={vantage_api_key}"

In [34]:
r = requests.get(url)

In [35]:
data = r.json()

In [36]:
data

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'LMT',
  '3. Last Refreshed': '2024-09-26',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2024-09-26': {'1. open': '575.0000',
   '2. high': '582.5300',
   '3. low': '574.4400',
   '4. close': '577.4000',
   '5. volume': '746294'},
  '2024-09-25': {'1. open': '581.5600',
   '2. high': '583.7500',
   '3. low': '576.8648',
   '4. close': '577.9400',
   '5. volume': '844517'},
  '2024-09-24': {'1. open': '578.9300',
   '2. high': '581.1600',
   '3. low': '576.1500',
   '4. close': '578.6300',
   '5. volume': '690123'},
  '2024-09-23': {'1. open': '571.5000',
   '2. high': '581.7500',
   '3. low': '570.8200',
   '4. close': '580.5100',
   '5. volume': '884699'},
  '2024-09-20': {'1. open': '563.0800',
   '2. high': '573.5000',
   '3. low': '562.9400',
   '4. close': '571.9200',
   '5. volume': '3794353'},
  '2024-09-19': {'1. open': '566.4700',
   '2. high': '567.5250',
   '3. low': '562.1629',
   '4. close': '565.1800',
   '5. volume': '917669'},
  '2024-09-18': {'1. open': '566.3200',
   '2. high': '569.5400',
   '3. low': '562.2800',
   '4. close': '565.4900',
   '5. volume': '731817'},
  '2024-09-17': {'1. open': '566.6600',
   '2. high': '568.1100',
   '3. low': '563.6001',
   '4. close': '567.0100',
   '5. volume': '739890'},
  '2024-09-16': {'1. open': '574.4100',
   '2. high': '577.0000',
   '3. low': '568.9901',
   '4. close': '572.9200',
   '5. volume': '597813'},
  '2024-09-13': {'1. open': '567.0000',
   '2. high': '572.4554',
   '3. low': '564.5300',
   '4. close': '569.9100',
   '5. volume': '638809'},
  '2024-09-12': {'1. open': '565.0000',
   '2. high': '568.9700',
   '3. low': '563.9000',
   '4. close': '568.2700',
   '5. volume': '739418'},
  '2024-09-11': {'1. open': '571.2000',
   '2. high': '572.4100',
   '3. low': '561.0701',
   '4. close': '566.9600',
   '5. volume': '809242'},
  '2024-09-10': {'1. open': '577.5600',
   '2. high': '577.8525',
   '3. low': '570.4200',
   '4. close': '572.1900',
   '5. volume': '756528'},
  '2024-09-09': {'1. open': '567.5100',
   '2. high': '578.0000',
   '3. low': '567.4800',
   '4. close': '576.5700',
   '5. volume': '810168'},
  '2024-09-06': {'1. open': '569.0500',
   '2. high': '572.1100',
   '3. low': '564.9500',
   '4. close': '566.6300',
   '5. volume': '976688'},
  '2024-09-05': {'1. open': '575.2000',
   '2. high': '575.9200',
   '3. low': '564.4100',
   '4. close': '568.5900',
   '5. volume': '841029'},
  '2024-09-04': {'1. open': '569.3400',
   '2. high': '578.7300',
   '3. low': '568.7200',
   '4. close': '574.7800',
   '5. volume': '893848'},
  '2024-09-03': {'1. open': '567.3300',
   '2. high': '572.0000',
   '3. low': '565.1900',
   '4. close': '567.2200',
   '5. volume': '1267110'},
  '2024-08-30': {'1. open': '564.9700',
   '2. high': '569.0900',
   '3. low': '562.5500',
   '4. close': '568.1000',
   '5. volume': '1082809'},
  '2024-08-29': {'1. open': '564.0000',
   '2. high': '568.5700',
   '3. low': '563.0000',
   '4. close': '566.8500',
   '5. volume': '662462'},
  '2024-08-28': {'1. open': '562.2000',
   '2. high': '568.7300',
   '3. low': '561.7800',
   '4. close': '563.9800',
   '5. volume': '829310'},
  '2024-08-27': {'1. open': '559.4500',
   '2. high': '562.1901',
   '3. low': '557.0200',
   '4. close': '560.4100',
   '5. volume': '749831'},
  '2024-08-26': {'1. open': '556.1100',
   '2. high': '560.1400',
   '3. low': '556.1100',
   '4. close': '558.1000',
   '5. volume': '795360'},
  '2024-08-23': {'1. open': '558.0000',
   '2. high': '558.8700',
   '3. low': '552.7800',
   '4. close': '555.0100',
   '5. volume': '870355'},
  '2024-08-22': {'1. open': '554.1800',
   '2. high': '558.1801',
   '3. low': '553.2701',
   '4. close': '557.0300',
   '5. volume': '774578'},
  '2024-08-21': {'1. open': '558.3800',
   '2. high': '559.9899',
   '3. low': '553.3100',
   '4. close': '553.7600',
   '5. volume': '883062'},
  '2024-08-20': {'1. open': '557.9700',
   '2. high': '558.9000',
   '3. low': '550.9600',
   '4. close': '557.0100',
   '5. volume': '972254'},
  '2024-08-19': {'1. open': '555.3200',
   '2. high': '562.7600',
   '3. low': '555.2500',
   '4. close': '558.3900',
   '5. volume': '709735'},
  '2024-08-16': {'1. open': '561.3000',
   '2. high': '562.4250',
   '3. low': '557.0000',
   '4. close': '560.1300',
   '5. volume': '912022'},
  '2024-08-15': {'1. open': '561.8000',
   '2. high': '564.0800',
   '3. low': '558.8300',
   '4. close': '560.2900',
   '5. volume': '974590'},
  '2024-08-14': {'1. open': '558.0800',
   '2. high': '564.2200',
   '3. low': '557.0000',
   '4. close': '563.2200',
   '5. volume': '796727'},
  '2024-08-13': {'1. open': '556.9000',
   '2. high': '559.6900',
   '3. low': '552.3100',
   '4. close': '559.4200',
   '5. volume': '793610'},
  '2024-08-12': {'1. open': '551.0700',
   '2. high': '557.5600',
   '3. low': '550.4000',
   '4. close': '556.9100',
   '5. volume': '793920'},
  '2024-08-09': {'1. open': '552.1600',
   '2. high': '553.6107',
   '3. low': '548.1295',
   '4. close': '551.5800',
   '5. volume': '825286'},
  '2024-08-08': {'1. open': '545.5100',
   '2. high': '553.6850',
   '3. low': '543.6900',
   '4. close': '551.6200',
   '5. volume': '846337'},
  '2024-08-07': {'1. open': '539.8700',
   '2. high': '552.1700',
   '3. low': '536.7374',
   '4. close': '548.5100',
   '5. volume': '1306584'},
  '2024-08-06': {'1. open': '545.9800',
   '2. high': '549.4800',
   '3. low': '541.1400',
   '4. close': '541.5600',
   '5. volume': '1033745'},
  '2024-08-05': {'1. open': '553.1600',
   '2. high': '562.6000',
   '3. low': '538.2400',
   '4. close': '545.3800',
   '5. volume': '1683773'},
  '2024-08-02': {'1. open': '551.1200',
   '2. high': '561.1200',
   '3. low': '541.3900',
   '4. close': '548.7700',
   '5. volume': '1484756'},
  '2024-08-01': {'1. open': '544.0400',
   '2. high': '549.1200',
   '3. low': '540.6900',
   '4. close': '548.8600',
   '5. volume': '1271748'},
  '2024-07-31': {'1. open': '543.0000',
   '2. high': '547.0000',
   '3. low': '538.1800',
   '4. close': '541.9200',
   '5. volume': '1481529'},
  '2024-07-30': {'1. open': '527.9500',
   '2. high': '538.4600',
   '3. low': '525.0300',
   '4. close': '537.6600',
   '5. volume': '1234234'},
  '2024-07-29': {'1. open': '523.0000',
   '2. high': '529.4600',
   '3. low': '519.2600',
   '4. close': '527.6400',
   '5. volume': '961345'},
  '2024-07-26': {'1. open': '522.2900',
   '2. high': '528.6400',
   '3. low': '520.0110',
   '4. close': '524.8000',
   '5. volume': '1141310'},
  '2024-07-25': {'1. open': '515.0000',
   '2. high': '526.6900',
   '3. low': '512.8700',
   '4. close': '521.4000',
   '5. volume': '1923901'},
  '2024-07-24': {'1. open': '505.0000',
   '2. high': '519.5900',
   '3. low': '501.4100',
   '4. close': '515.2000',
   '5. volume': '2580066'},
  '2024-07-23': {'1. open': '488.8400',
   '2. high': '501.7700',
   '3. low': '482.8600',
   '4. close': '501.2900',
   '5. volume': '2579132'},
  '2024-07-22': {'1. open': '475.0000',
   '2. high': '476.1300',
   '3. low': '472.8500',
   '4. close': '474.5900',
   '5. volume': '881562'},
  '2024-07-19': {'1. open': '479.5400',
   '2. high': '479.5400',
   '3. low': '472.8143',
   '4. close': '474.9200',
   '5. volume': '889361'},
  '2024-07-18': {'1. open': '474.5000',
   '2. high': '480.8600',
   '3. low': '473.0150',
   '4. close': '476.0000',
   '5. volume': '981061'},
  '2024-07-17': {'1. open': '470.0000',
   '2. high': '476.7750',
   '3. low': '469.7045',
   '4. close': '476.0700',
   '5. volume': '1123060'},
  '2024-07-16': {'1. open': '463.7500',
   '2. high': '469.1900',
   '3. low': '463.7500',
   '4. close': '468.5800',
   '5. volume': '736547'},
  '2024-07-15': {'1. open': '466.7100',
   '2. high': '467.2500',
   '3. low': '462.7800',
   '4. close': '463.8800',
   '5. volume': '783092'},
  '2024-07-12': {'1. open': '462.3600',
   '2. high': '464.9000',
   '3. low': '459.5300',
   '4. close': '463.7300',
   '5. volume': '579436'},
  '2024-07-11': {'1. open': '459.9200',
   '2. high': '465.7700',
   '3. low': '456.1100',
   '4. close': '460.3800',
   '5. volume': '1132976'},
  '2024-07-10': {'1. open': '460.3700',
   '2. high': '461.3900',
   '3. low': '457.2500',
   '4. close': '461.0100',
   '5. volume': '655973'},
  '2024-07-09': {'1. open': '461.7000',
   '2. high': '462.6199',
   '3. low': '459.7600',
   '4. close': '460.3000',
   '5. volume': '537209'},
  '2024-07-08': {'1. open': '462.6800',
   '2. high': '464.5700',
   '3. low': '461.1200',
   '4. close': '461.7600',
   '5. volume': '447867'},
  '2024-07-05': {'1. open': '464.9800',
   '2. high': '465.0000',
   '3. low': '459.6900',
   '4. close': '462.1600',
   '5. volume': '631595'},
  '2024-07-03': {'1. open': '465.4900',
   '2. high': '466.4700',
   '3. low': '464.1298',
   '4. close': '466.0300',
   '5. volume': '313283'},
  '2024-07-02': {'1. open': '465.6000',
   '2. high': '466.6700',
   '3. low': '464.0201',
   '4. close': '465.7000',
   '5. volume': '502492'},
  '2024-07-01': {'1. open': '470.7700',
   '2. high': '471.6800',
   '3. low': '464.7600',
   '4. close': '466.4400',
   '5. volume': '562562'},
  '2024-06-28': {'1. open': '470.0500',
   '2. high': '471.7499',
   '3. low': '464.8700',
   '4. close': '467.1000',
   '5. volume': '3472549'},
  '2024-06-27': {'1. open': '468.8800',
   '2. high': '468.8800',
   '3. low': '465.3050',
   '4. close': '467.1300',
   '5. volume': '871215'},
  '2024-06-26': {'1. open': '467.0000',
   '2. high': '468.1000',
   '3. low': '463.7200',
   '4. close': '466.9900',
   '5. volume': '932061'},
  '2024-06-25': {'1. open': '470.8200',
   '2. high': '471.6200',
   '3. low': '466.6600',
   '4. close': '468.0700',
   '5. volume': '715816'},
  '2024-06-24': {'1. open': '468.9600',
   '2. high': '475.6900',
   '3. low': '467.8200',
   '4. close': '471.5100',
   '5. volume': '1031607'},
  '2024-06-21': {'1. open': '467.1500',
   '2. high': '469.8000',
   '3. low': '463.6500',
   '4. close': '467.6000',
   '5. volume': '3365244'},
  '2024-06-20': {'1. open': '460.0000',
   '2. high': '467.4899',
   '3. low': '459.1600',
   '4. close': '466.3400',
   '5. volume': '1041412'},
  '2024-06-18': {'1. open': '459.8000',
   '2. high': '460.7000',
   '3. low': '457.3900',
   '4. close': '460.0000',
   '5. volume': '658084'},
  '2024-06-17': {'1. open': '457.7500',
   '2. high': '459.1900',
   '3. low': '456.3050',
   '4. close': '459.0100',
   '5. volume': '669784'},
  '2024-06-14': {'1. open': '456.5000',
   '2. high': '458.5600',
   '3. low': '454.4400',
   '4. close': '458.3400',
   '5. volume': '702880'},
  '2024-06-13': {'1. open': '458.6400',
   '2. high': '459.7500',
   '3. low': '456.0100',
   '4. close': '458.5600',
   '5. volume': '742025'},
  '2024-06-12': {'1. open': '462.3000',
   '2. high': '463.2300',
   '3. low': '457.6650',
   '4. close': '459.1100',
   '5. volume': '1026596'},
  '2024-06-11': {'1. open': '465.6800',
   '2. high': '466.5834',
   '3. low': '462.5750',
   '4. close': '462.8000',
   '5. volume': '908416'},
  '2024-06-10': {'1. open': '470.7500',
   '2. high': '470.7500',
   '3. low': '465.7550',
   '4. close': '467.4600',
   '5. volume': '900460'},
  '2024-06-07': {'1. open': '468.8100',
   '2. high': '475.2900',
   '3. low': '468.6200',
   '4. close': '470.1300',
   '5. volume': '1042800'},
  '2024-06-06': {'1. open': '465.2300',
   '2. high': '469.7900',
   '3. low': '464.3500',
   '4. close': '468.6200',
   '5. volume': '768313'},
  '2024-06-05': {'1. open': '468.4200',
   '2. high': '468.8500',
   '3. low': '463.6180',
   '4. close': '465.2300',
   '5. volume': '915412'},
  '2024-06-04': {'1. open': '467.5100',
   '2. high': '470.1600',
   '3. low': '466.1600',
   '4. close': '468.8900',
   '5. volume': '845778'},
  '2024-06-03': {'1. open': '466.0000',
   '2. high': '470.5200',
   '3. low': '465.0100',
   '4. close': '467.6000',
   '5. volume': '990132'},
  '2024-05-31': {'1. open': '460.9000',
   '2. high': '470.3600',
   '3. low': '459.4900',
   '4. close': '470.3400',
   '5. volume': '1651560'},
  '2024-05-30': {'1. open': '455.0000',
   '2. high': '462.9400',
   '3. low': '455.0000',
   '4. close': '460.9400',
   '5. volume': '1173703'},
  '2024-05-29': {'1. open': '455.9800',
   '2. high': '456.0000',
   '3. low': '451.8000',
   '4. close': '452.7200',
   '5. volume': '1267964'},
  '2024-05-28': {'1. open': '465.6100',
   '2. high': '466.0000',
   '3. low': '457.2500',
   '4. close': '458.4800',
   '5. volume': '1150758'},
  '2024-05-24': {'1. open': '467.6700',
   '2. high': '468.6600',
   '3. low': '465.4700',
   '4. close': '467.3500',
   '5. volume': '513802'},
  '2024-05-23': {'1. open': '468.0900',
   '2. high': '469.6800',
   '3. low': '466.2300',
   '4. close': '467.0800',
   '5. volume': '866955'},
  '2024-05-22': {'1. open': '467.4700',
   '2. high': '469.9000',
   '3. low': '466.7800',
   '4. close': '469.7100',
   '5. volume': '548809'},
  '2024-05-21': {'1. open': '468.0000',
   '2. high': '469.1200',
   '3. low': '466.8400',
   '4. close': '468.3100',
   '5. volume': '558976'},
  '2024-05-20': {'1. open': '467.7700',
   '2. high': '468.7700',
   '3. low': '464.9200',
   '4. close': '467.0800',
   '5. volume': '735291'},
  '2024-05-17': {'1. open': '465.8400',
   '2. high': '467.0000',
   '3. low': '463.1500',
   '4. close': '466.2000',
   '5. volume': '677219'},
  '2024-05-16': {'1. open': '463.6000',
   '2. high': '468.3200',
   '3. low': '453.0000',
   '4. close': '464.8300',
   '5. volume': '1130786'},
  '2024-05-15': {'1. open': '466.2800',
   '2. high': '467.4000',
   '3. low': '463.5100',
   '4. close': '464.0800',
   '5. volume': '804062'},
  '2024-05-14': {'1. open': '471.1100',
   '2. high': '471.1100',
   '3. low': '466.8000',
   '4. close': '467.1800',
   '5. volume': '565691'},
  '2024-05-13': {'1. open': '469.8800',
   '2. high': '472.3450',
   '3. low': '469.5000',
   '4. close': '470.5600',
   '5. volume': '634358'},
  '2024-05-10': {'1. open': '469.0000',
   '2. high': '470.6200',
   '3. low': '467.9750',
   '4. close': '468.8800',
   '5. volume': '482564'},
  '2024-05-09': {'1. open': '466.0800',
   '2. high': '468.7600',
   '3. low': '465.2101',
   '4. close': '468.3900',
   '5. volume': '595046'},
  '2024-05-08': {'1. open': '467.5000',
   '2. high': '468.0000',
   '3. low': '463.7800',
   '4. close': '466.1600',
   '5. volume': '599051'},
  '2024-05-07': {'1. open': '464.0000',
   '2. high': '466.8100',
   '3. low': '463.1600',
   '4. close': '466.6800',
   '5. volume': '723436'},
  '2024-05-06': {'1. open': '463.1600',
   '2. high': '463.4999',
   '3. low': '460.1800',
   '4. close': '462.7800',
   '5. volume': '796391'}}}

In [37]:
data["Time Series (Daily)"]

{'2024-09-26': {'1. open': '575.0000',
  '2. high': '582.5300',
  '3. low': '574.4400',
  '4. close': '577.4000',
  '5. volume': '746294'},
 '2024-09-25': {'1. open': '581.5600',
  '2. high': '583.7500',
  '3. low': '576.8648',
  '4. close': '577.9400',
  '5. volume': '844517'},
 '2024-09-24': {'1. open': '578.9300',
  '2. high': '581.1600',
  '3. low': '576.1500',
  '4. close': '578.6300',
  '5. volume': '690123'},
 '2024-09-23': {'1. open': '571.5000',
  '2. high': '581.7500',
  '3. low': '570.8200',
  '4. close': '580.5100',
  '5. volume': '884699'},
 '2024-09-20': {'1. open': '563.0800',
  '2. high': '573.5000',
  '3. low': '562.9400',
  '4. close': '571.9200',
  '5. volume': '3794353'},
 '2024-09-19': {'1. open': '566.4700',
  '2. high': '567.5250',
  '3. low': '562.1629',
  '4. close': '565.1800',
  '5. volume': '917669'},
 '2024-09-18': {'1. open': '566.3200',
  '2. high': '569.5400',
  '3. low': '562.2800',
  '4. close': '565.4900',
  '5. volume': '731817'},
 '2024-09-17': {'1. open': '566.6600',
  '2. high': '568.1100',
  '3. low': '563.6001',
  '4. close': '567.0100',
  '5. volume': '739890'},
 '2024-09-16': {'1. open': '574.4100',
  '2. high': '577.0000',
  '3. low': '568.9901',
  '4. close': '572.9200',
  '5. volume': '597813'},
 '2024-09-13': {'1. open': '567.0000',
  '2. high': '572.4554',
  '3. low': '564.5300',
  '4. close': '569.9100',
  '5. volume': '638809'},
 '2024-09-12': {'1. open': '565.0000',
  '2. high': '568.9700',
  '3. low': '563.9000',
  '4. close': '568.2700',
  '5. volume': '739418'},
 '2024-09-11': {'1. open': '571.2000',
  '2. high': '572.4100',
  '3. low': '561.0701',
  '4. close': '566.9600',
  '5. volume': '809242'},
 '2024-09-10': {'1. open': '577.5600',
  '2. high': '577.8525',
  '3. low': '570.4200',
  '4. close': '572.1900',
  '5. volume': '756528'},
 '2024-09-09': {'1. open': '567.5100',
  '2. high': '578.0000',
  '3. low': '567.4800',
  '4. close': '576.5700',
  '5. volume': '810168'},
 '2024-09-06': {'1. open': '569.0500',
  '2. high': '572.1100',
  '3. low': '564.9500',
  '4. close': '566.6300',
  '5. volume': '976688'},
 '2024-09-05': {'1. open': '575.2000',
  '2. high': '575.9200',
  '3. low': '564.4100',
  '4. close': '568.5900',
  '5. volume': '841029'},
 '2024-09-04': {'1. open': '569.3400',
  '2. high': '578.7300',
  '3. low': '568.7200',
  '4. close': '574.7800',
  '5. volume': '893848'},
 '2024-09-03': {'1. open': '567.3300',
  '2. high': '572.0000',
  '3. low': '565.1900',
  '4. close': '567.2200',
  '5. volume': '1267110'},
 '2024-08-30': {'1. open': '564.9700',
  '2. high': '569.0900',
  '3. low': '562.5500',
  '4. close': '568.1000',
  '5. volume': '1082809'},
 '2024-08-29': {'1. open': '564.0000',
  '2. high': '568.5700',
  '3. low': '563.0000',
  '4. close': '566.8500',
  '5. volume': '662462'},
 '2024-08-28': {'1. open': '562.2000',
  '2. high': '568.7300',
  '3. low': '561.7800',
  '4. close': '563.9800',
  '5. volume': '829310'},
 '2024-08-27': {'1. open': '559.4500',
  '2. high': '562.1901',
  '3. low': '557.0200',
  '4. close': '560.4100',
  '5. volume': '749831'},
 '2024-08-26': {'1. open': '556.1100',
  '2. high': '560.1400',
  '3. low': '556.1100',
  '4. close': '558.1000',
  '5. volume': '795360'},
 '2024-08-23': {'1. open': '558.0000',
  '2. high': '558.8700',
  '3. low': '552.7800',
  '4. close': '555.0100',
  '5. volume': '870355'},
 '2024-08-22': {'1. open': '554.1800',
  '2. high': '558.1801',
  '3. low': '553.2701',
  '4. close': '557.0300',
  '5. volume': '774578'},
 '2024-08-21': {'1. open': '558.3800',
  '2. high': '559.9899',
  '3. low': '553.3100',
  '4. close': '553.7600',
  '5. volume': '883062'},
 '2024-08-20': {'1. open': '557.9700',
  '2. high': '558.9000',
  '3. low': '550.9600',
  '4. close': '557.0100',
  '5. volume': '972254'},
 '2024-08-19': {'1. open': '555.3200',
  '2. high': '562.7600',
  '3. low': '555.2500',
  '4. close': '558.3900',
  '5. volume': '709735'},
 '2024-08-16': {'1. open': '561.3000',
  '2. high': '562.4250',
  '3. low': '557.0000',
  '4. close': '560.1300',
  '5. volume': '912022'},
 '2024-08-15': {'1. open': '561.8000',
  '2. high': '564.0800',
  '3. low': '558.8300',
  '4. close': '560.2900',
  '5. volume': '974590'},
 '2024-08-14': {'1. open': '558.0800',
  '2. high': '564.2200',
  '3. low': '557.0000',
  '4. close': '563.2200',
  '5. volume': '796727'},
 '2024-08-13': {'1. open': '556.9000',
  '2. high': '559.6900',
  '3. low': '552.3100',
  '4. close': '559.4200',
  '5. volume': '793610'},
 '2024-08-12': {'1. open': '551.0700',
  '2. high': '557.5600',
  '3. low': '550.4000',
  '4. close': '556.9100',
  '5. volume': '793920'},
 '2024-08-09': {'1. open': '552.1600',
  '2. high': '553.6107',
  '3. low': '548.1295',
  '4. close': '551.5800',
  '5. volume': '825286'},
 '2024-08-08': {'1. open': '545.5100',
  '2. high': '553.6850',
  '3. low': '543.6900',
  '4. close': '551.6200',
  '5. volume': '846337'},
 '2024-08-07': {'1. open': '539.8700',
  '2. high': '552.1700',
  '3. low': '536.7374',
  '4. close': '548.5100',
  '5. volume': '1306584'},
 '2024-08-06': {'1. open': '545.9800',
  '2. high': '549.4800',
  '3. low': '541.1400',
  '4. close': '541.5600',
  '5. volume': '1033745'},
 '2024-08-05': {'1. open': '553.1600',
  '2. high': '562.6000',
  '3. low': '538.2400',
  '4. close': '545.3800',
  '5. volume': '1683773'},
 '2024-08-02': {'1. open': '551.1200',
  '2. high': '561.1200',
  '3. low': '541.3900',
  '4. close': '548.7700',
  '5. volume': '1484756'},
 '2024-08-01': {'1. open': '544.0400',
  '2. high': '549.1200',
  '3. low': '540.6900',
  '4. close': '548.8600',
  '5. volume': '1271748'},
 '2024-07-31': {'1. open': '543.0000',
  '2. high': '547.0000',
  '3. low': '538.1800',
  '4. close': '541.9200',
  '5. volume': '1481529'},
 '2024-07-30': {'1. open': '527.9500',
  '2. high': '538.4600',
  '3. low': '525.0300',
  '4. close': '537.6600',
  '5. volume': '1234234'},
 '2024-07-29': {'1. open': '523.0000',
  '2. high': '529.4600',
  '3. low': '519.2600',
  '4. close': '527.6400',
  '5. volume': '961345'},
 '2024-07-26': {'1. open': '522.2900',
  '2. high': '528.6400',
  '3. low': '520.0110',
  '4. close': '524.8000',
  '5. volume': '1141310'},
 '2024-07-25': {'1. open': '515.0000',
  '2. high': '526.6900',
  '3. low': '512.8700',
  '4. close': '521.4000',
  '5. volume': '1923901'},
 '2024-07-24': {'1. open': '505.0000',
  '2. high': '519.5900',
  '3. low': '501.4100',
  '4. close': '515.2000',
  '5. volume': '2580066'},
 '2024-07-23': {'1. open': '488.8400',
  '2. high': '501.7700',
  '3. low': '482.8600',
  '4. close': '501.2900',
  '5. volume': '2579132'},
 '2024-07-22': {'1. open': '475.0000',
  '2. high': '476.1300',
  '3. low': '472.8500',
  '4. close': '474.5900',
  '5. volume': '881562'},
 '2024-07-19': {'1. open': '479.5400',
  '2. high': '479.5400',
  '3. low': '472.8143',
  '4. close': '474.9200',
  '5. volume': '889361'},
 '2024-07-18': {'1. open': '474.5000',
  '2. high': '480.8600',
  '3. low': '473.0150',
  '4. close': '476.0000',
  '5. volume': '981061'},
 '2024-07-17': {'1. open': '470.0000',
  '2. high': '476.7750',
  '3. low': '469.7045',
  '4. close': '476.0700',
  '5. volume': '1123060'},
 '2024-07-16': {'1. open': '463.7500',
  '2. high': '469.1900',
  '3. low': '463.7500',
  '4. close': '468.5800',
  '5. volume': '736547'},
 '2024-07-15': {'1. open': '466.7100',
  '2. high': '467.2500',
  '3. low': '462.7800',
  '4. close': '463.8800',
  '5. volume': '783092'},
 '2024-07-12': {'1. open': '462.3600',
  '2. high': '464.9000',
  '3. low': '459.5300',
  '4. close': '463.7300',
  '5. volume': '579436'},
 '2024-07-11': {'1. open': '459.9200',
  '2. high': '465.7700',
  '3. low': '456.1100',
  '4. close': '460.3800',
  '5. volume': '1132976'},
 '2024-07-10': {'1. open': '460.3700',
  '2. high': '461.3900',
  '3. low': '457.2500',
  '4. close': '461.0100',
  '5. volume': '655973'},
 '2024-07-09': {'1. open': '461.7000',
  '2. high': '462.6199',
  '3. low': '459.7600',
  '4. close': '460.3000',
  '5. volume': '537209'},
 '2024-07-08': {'1. open': '462.6800',
  '2. high': '464.5700',
  '3. low': '461.1200',
  '4. close': '461.7600',
  '5. volume': '447867'},
 '2024-07-05': {'1. open': '464.9800',
  '2. high': '465.0000',
  '3. low': '459.6900',
  '4. close': '462.1600',
  '5. volume': '631595'},
 '2024-07-03': {'1. open': '465.4900',
  '2. high': '466.4700',
  '3. low': '464.1298',
  '4. close': '466.0300',
  '5. volume': '313283'},
 '2024-07-02': {'1. open': '465.6000',
  '2. high': '466.6700',
  '3. low': '464.0201',
  '4. close': '465.7000',
  '5. volume': '502492'},
 '2024-07-01': {'1. open': '470.7700',
  '2. high': '471.6800',
  '3. low': '464.7600',
  '4. close': '466.4400',
  '5. volume': '562562'},
 '2024-06-28': {'1. open': '470.0500',
  '2. high': '471.7499',
  '3. low': '464.8700',
  '4. close': '467.1000',
  '5. volume': '3472549'},
 '2024-06-27': {'1. open': '468.8800',
  '2. high': '468.8800',
  '3. low': '465.3050',
  '4. close': '467.1300',
  '5. volume': '871215'},
 '2024-06-26': {'1. open': '467.0000',
  '2. high': '468.1000',
  '3. low': '463.7200',
  '4. close': '466.9900',
  '5. volume': '932061'},
 '2024-06-25': {'1. open': '470.8200',
  '2. high': '471.6200',
  '3. low': '466.6600',
  '4. close': '468.0700',
  '5. volume': '715816'},
 '2024-06-24': {'1. open': '468.9600',
  '2. high': '475.6900',
  '3. low': '467.8200',
  '4. close': '471.5100',
  '5. volume': '1031607'},
 '2024-06-21': {'1. open': '467.1500',
  '2. high': '469.8000',
  '3. low': '463.6500',
  '4. close': '467.6000',
  '5. volume': '3365244'},
 '2024-06-20': {'1. open': '460.0000',
  '2. high': '467.4899',
  '3. low': '459.1600',
  '4. close': '466.3400',
  '5. volume': '1041412'},
 '2024-06-18': {'1. open': '459.8000',
  '2. high': '460.7000',
  '3. low': '457.3900',
  '4. close': '460.0000',
  '5. volume': '658084'},
 '2024-06-17': {'1. open': '457.7500',
  '2. high': '459.1900',
  '3. low': '456.3050',
  '4. close': '459.0100',
  '5. volume': '669784'},
 '2024-06-14': {'1. open': '456.5000',
  '2. high': '458.5600',
  '3. low': '454.4400',
  '4. close': '458.3400',
  '5. volume': '702880'},
 '2024-06-13': {'1. open': '458.6400',
  '2. high': '459.7500',
  '3. low': '456.0100',
  '4. close': '458.5600',
  '5. volume': '742025'},
 '2024-06-12': {'1. open': '462.3000',
  '2. high': '463.2300',
  '3. low': '457.6650',
  '4. close': '459.1100',
  '5. volume': '1026596'},
 '2024-06-11': {'1. open': '465.6800',
  '2. high': '466.5834',
  '3. low': '462.5750',
  '4. close': '462.8000',
  '5. volume': '908416'},
 '2024-06-10': {'1. open': '470.7500',
  '2. high': '470.7500',
  '3. low': '465.7550',
  '4. close': '467.4600',
  '5. volume': '900460'},
 '2024-06-07': {'1. open': '468.8100',
  '2. high': '475.2900',
  '3. low': '468.6200',
  '4. close': '470.1300',
  '5. volume': '1042800'},
 '2024-06-06': {'1. open': '465.2300',
  '2. high': '469.7900',
  '3. low': '464.3500',
  '4. close': '468.6200',
  '5. volume': '768313'},
 '2024-06-05': {'1. open': '468.4200',
  '2. high': '468.8500',
  '3. low': '463.6180',
  '4. close': '465.2300',
  '5. volume': '915412'},
 '2024-06-04': {'1. open': '467.5100',
  '2. high': '470.1600',
  '3. low': '466.1600',
  '4. close': '468.8900',
  '5. volume': '845778'},
 '2024-06-03': {'1. open': '466.0000',
  '2. high': '470.5200',
  '3. low': '465.0100',
  '4. close': '467.6000',
  '5. volume': '990132'},
 '2024-05-31': {'1. open': '460.9000',
  '2. high': '470.3600',
  '3. low': '459.4900',
  '4. close': '470.3400',
  '5. volume': '1651560'},
 '2024-05-30': {'1. open': '455.0000',
  '2. high': '462.9400',
  '3. low': '455.0000',
  '4. close': '460.9400',
  '5. volume': '1173703'},
 '2024-05-29': {'1. open': '455.9800',
  '2. high': '456.0000',
  '3. low': '451.8000',
  '4. close': '452.7200',
  '5. volume': '1267964'},
 '2024-05-28': {'1. open': '465.6100',
  '2. high': '466.0000',
  '3. low': '457.2500',
  '4. close': '458.4800',
  '5. volume': '1150758'},
 '2024-05-24': {'1. open': '467.6700',
  '2. high': '468.6600',
  '3. low': '465.4700',
  '4. close': '467.3500',
  '5. volume': '513802'},
 '2024-05-23': {'1. open': '468.0900',
  '2. high': '469.6800',
  '3. low': '466.2300',
  '4. close': '467.0800',
  '5. volume': '866955'},
 '2024-05-22': {'1. open': '467.4700',
  '2. high': '469.9000',
  '3. low': '466.7800',
  '4. close': '469.7100',
  '5. volume': '548809'},
 '2024-05-21': {'1. open': '468.0000',
  '2. high': '469.1200',
  '3. low': '466.8400',
  '4. close': '468.3100',
  '5. volume': '558976'},
 '2024-05-20': {'1. open': '467.7700',
  '2. high': '468.7700',
  '3. low': '464.9200',
  '4. close': '467.0800',
  '5. volume': '735291'},
 '2024-05-17': {'1. open': '465.8400',
  '2. high': '467.0000',
  '3. low': '463.1500',
  '4. close': '466.2000',
  '5. volume': '677219'},
 '2024-05-16': {'1. open': '463.6000',
  '2. high': '468.3200',
  '3. low': '453.0000',
  '4. close': '464.8300',
  '5. volume': '1130786'},
 '2024-05-15': {'1. open': '466.2800',
  '2. high': '467.4000',
  '3. low': '463.5100',
  '4. close': '464.0800',
  '5. volume': '804062'},
 '2024-05-14': {'1. open': '471.1100',
  '2. high': '471.1100',
  '3. low': '466.8000',
  '4. close': '467.1800',
  '5. volume': '565691'},
 '2024-05-13': {'1. open': '469.8800',
  '2. high': '472.3450',
  '3. low': '469.5000',
  '4. close': '470.5600',
  '5. volume': '634358'},
 '2024-05-10': {'1. open': '469.0000',
  '2. high': '470.6200',
  '3. low': '467.9750',
  '4. close': '468.8800',
  '5. volume': '482564'},
 '2024-05-09': {'1. open': '466.0800',
  '2. high': '468.7600',
  '3. low': '465.2101',
  '4. close': '468.3900',
  '5. volume': '595046'},
 '2024-05-08': {'1. open': '467.5000',
  '2. high': '468.0000',
  '3. low': '463.7800',
  '4. close': '466.1600',
  '5. volume': '599051'},
 '2024-05-07': {'1. open': '464.0000',
  '2. high': '466.8100',
  '3. low': '463.1600',
  '4. close': '466.6800',
  '5. volume': '723436'},
 '2024-05-06': {'1. open': '463.1600',
  '2. high': '463.4999',
  '3. low': '460.1800',
  '4. close': '462.7800',
  '5. volume': '796391'}}

In [42]:
for d in data["Time Series (Daily)"]:
    print(d)

2024-09-26
2024-09-25
2024-09-24
2024-09-23
2024-09-20
2024-09-19
2024-09-18
2024-09-17
2024-09-16
2024-09-13
2024-09-12
2024-09-11
2024-09-10
2024-09-09
2024-09-06
2024-09-05
2024-09-04
2024-09-03
2024-08-30
2024-08-29
2024-08-28
2024-08-27
2024-08-26
2024-08-23
2024-08-22
2024-08-21
2024-08-20
2024-08-19
2024-08-16
2024-08-15
2024-08-14
2024-08-13
2024-08-12
2024-08-09
2024-08-08
2024-08-07
2024-08-06
2024-08-05
2024-08-02
2024-08-01
2024-07-31
2024-07-30
2024-07-29
2024-07-26
2024-07-25
2024-07-24
2024-07-23
2024-07-22
2024-07-19
2024-07-18
2024-07-17
2024-07-16
2024-07-15
2024-07-12
2024-07-11
2024-07-10
2024-07-09
2024-07-08
2024-07-05
2024-07-03
2024-07-02
2024-07-01
2024-06-28
2024-06-27
2024-06-26
2024-06-25
2024-06-24
2024-06-21
2024-06-20
2024-06-18
2024-06-17
2024-06-14
2024-06-13
2024-06-12
2024-06-11
2024-06-10
2024-06-07
2024-06-06
2024-06-05
2024-06-04
2024-06-03
2024-05-31
2024-05-30
2024-05-29
2024-05-28
2024-05-24
2024-05-23
2024-05-22
2024-05-21
2024-05-20
2024-05-17
2024-05-16
2024-05-15
2024-05-14
2024-05-13
2024-05-10
2024-05-09
2024-05-08
2024-05-07
2024-05-06

In [43]:
data["Time Series (Daily)"]["2024-09-25"]

{'1. open': '581.5600',
 '2. high': '583.7500',
 '3. low': '576.8648',
 '4. close': '577.9400',
 '5. volume': '844517'}

In [44]:
data["Time Series (Daily)"]["2024-09-25"]["1. open"]

'581.5600'

In [52]:
def return_last_90d_price(symbol):
  """
   - return the last 90 days of the stock prices of symbol as a list of json strings
  """
  vantage_api_key = userdata.get('vantage_api_key')
  url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={vantage_api_key}'
  r = requests.get(url)
  data = r.json()
  results = []   # empyt list for now to hold the 90 days of stock info (open, high, low, close, volume)
  for d in data["Time Series (Daily)"]:   # here d is a date: "YYYY-MM-DD"
    results.append(data["Time Series (Daily)"][d])
    # an example of data["Time Series (Daily)"][d] is
    # {'1. open': '117.3500', '2. high': '119.6600', '3. low': '117.2500', '4. close': '117.8700', '5. volume': '286038878'}
  return results

In [53]:
price_list = return_last_90d_price("LMT")

In [54]:
price_list

[{'1. open': '575.0000',
  '2. high': '582.5300',
  '3. low': '574.4400',
  '4. close': '577.4000',
  '5. volume': '746294'},
 {'1. open': '581.5600',
  '2. high': '583.7500',
  '3. low': '576.8648',
  '4. close': '577.9400',
  '5. volume': '844517'},
 {'1. open': '578.9300',
  '2. high': '581.1600',
  '3. low': '576.1500',
  '4. close': '578.6300',
  '5. volume': '690123'},
 {'1. open': '571.5000',
  '2. high': '581.7500',
  '3. low': '570.8200',
  '4. close': '580.5100',
  '5. volume': '884699'},
 {'1. open': '563.0800',
  '2. high': '573.5000',
  '3. low': '562.9400',
  '4. close': '571.9200',
  '5. volume': '3794353'},
 {'1. open': '566.4700',
  '2. high': '567.5250',
  '3. low': '562.1629',
  '4. close': '565.1800',
  '5. volume': '917669'},
 {'1. open': '566.3200',
  '2. high': '569.5400',
  '3. low': '562.2800',
  '4. close': '565.4900',
  '5. volume': '731817'},
 {'1. open': '566.6600',
  '2. high': '568.1100',
  '3. low': '563.6001',
  '4. close': '567.0100',
  '5. volume': '739890'},
 {'1. open': '574.4100',
  '2. high': '577.0000',
  '3. low': '568.9901',
  '4. close': '572.9200',
  '5. volume': '597813'},
 {'1. open': '567.0000',
  '2. high': '572.4554',
  '3. low': '564.5300',
  '4. close': '569.9100',
  '5. volume': '638809'},
 {'1. open': '565.0000',
  '2. high': '568.9700',
  '3. low': '563.9000',
  '4. close': '568.2700',
  '5. volume': '739418'},
 {'1. open': '571.2000',
  '2. high': '572.4100',
  '3. low': '561.0701',
  '4. close': '566.9600',
  '5. volume': '809242'},
 {'1. open': '577.5600',
  '2. high': '577.8525',
  '3. low': '570.4200',
  '4. close': '572.1900',
  '5. volume': '756528'},
 {'1. open': '567.5100',
  '2. high': '578.0000',
  '3. low': '567.4800',
  '4. close': '576.5700',
  '5. volume': '810168'},
 {'1. open': '569.0500',
  '2. high': '572.1100',
  '3. low': '564.9500',
  '4. close': '566.6300',
  '5. volume': '976688'},
 {'1. open': '575.2000',
  '2. high': '575.9200',
  '3. low': '564.4100',
  '4. close': '568.5900',
  '5. volume': '841029'},
 {'1. open': '569.3400',
  '2. high': '578.7300',
  '3. low': '568.7200',
  '4. close': '574.7800',
  '5. volume': '893848'},
 {'1. open': '567.3300',
  '2. high': '572.0000',
  '3. low': '565.1900',
  '4. close': '567.2200',
  '5. volume': '1267110'},
 {'1. open': '564.9700',
  '2. high': '569.0900',
  '3. low': '562.5500',
  '4. close': '568.1000',
  '5. volume': '1082809'},
 {'1. open': '564.0000',
  '2. high': '568.5700',
  '3. low': '563.0000',
  '4. close': '566.8500',
  '5. volume': '662462'},
 {'1. open': '562.2000',
  '2. high': '568.7300',
  '3. low': '561.7800',
  '4. close': '563.9800',
  '5. volume': '829310'},
 {'1. open': '559.4500',
  '2. high': '562.1901',
  '3. low': '557.0200',
  '4. close': '560.4100',
  '5. volume': '749831'},
 {'1. open': '556.1100',
  '2. high': '560.1400',
  '3. low': '556.1100',
  '4. close': '558.1000',
  '5. volume': '795360'},
 {'1. open': '558.0000',
  '2. high': '558.8700',
  '3. low': '552.7800',
  '4. close': '555.0100',
  '5. volume': '870355'},
 {'1. open': '554.1800',
  '2. high': '558.1801',
  '3. low': '553.2701',
  '4. close': '557.0300',
  '5. volume': '774578'},
 {'1. open': '558.3800',
  '2. high': '559.9899',
  '3. low': '553.3100',
  '4. close': '553.7600',
  '5. volume': '883062'},
 {'1. open': '557.9700',
  '2. high': '558.9000',
  '3. low': '550.9600',
  '4. close': '557.0100',
  '5. volume': '972254'},
 {'1. open': '555.3200',
  '2. high': '562.7600',
  '3. low': '555.2500',
  '4. close': '558.3900',
  '5. volume': '709735'},
 {'1. open': '561.3000',
  '2. high': '562.4250',
  '3. low': '557.0000',
  '4. close': '560.1300',
  '5. volume': '912022'},
 {'1. open': '561.8000',
  '2. high': '564.0800',
  '3. low': '558.8300',
  '4. close': '560.2900',
  '5. volume': '974590'},
 {'1. open': '558.0800',
  '2. high': '564.2200',
  '3. low': '557.0000',
  '4. close': '563.2200',
  '5. volume': '796727'},
 {'1. open': '556.9000',
  '2. high': '559.6900',
  '3. low': '552.3100',
  '4. close': '559.4200',
  '5. volume': '793610'},
 {'1. open': '551.0700',
  '2. high': '557.5600',
  '3. low': '550.4000',
  '4. close': '556.9100',
  '5. volume': '793920'},
 {'1. open': '552.1600',
  '2. high': '553.6107',
  '3. low': '548.1295',
  '4. close': '551.5800',
  '5. volume': '825286'},
 {'1. open': '545.5100',
  '2. high': '553.6850',
  '3. low': '543.6900',
  '4. close': '551.6200',
  '5. volume': '846337'},
 {'1. open': '539.8700',
  '2. high': '552.1700',
  '3. low': '536.7374',
  '4. close': '548.5100',
  '5. volume': '1306584'},
 {'1. open': '545.9800',
  '2. high': '549.4800',
  '3. low': '541.1400',
  '4. close': '541.5600',
  '5. volume': '1033745'},
 {'1. open': '553.1600',
  '2. high': '562.6000',
  '3. low': '538.2400',
  '4. close': '545.3800',
  '5. volume': '1683773'},
 {'1. open': '551.1200',
  '2. high': '561.1200',
  '3. low': '541.3900',
  '4. close': '548.7700',
  '5. volume': '1484756'},
 {'1. open': '544.0400',
  '2. high': '549.1200',
  '3. low': '540.6900',
  '4. close': '548.8600',
  '5. volume': '1271748'},
 {'1. open': '543.0000',
  '2. high': '547.0000',
  '3. low': '538.1800',
  '4. close': '541.9200',
  '5. volume': '1481529'},
 {'1. open': '527.9500',
  '2. high': '538.4600',
  '3. low': '525.0300',
  '4. close': '537.6600',
  '5. volume': '1234234'},
 {'1. open': '523.0000',
  '2. high': '529.4600',
  '3. low': '519.2600',
  '4. close': '527.6400',
  '5. volume': '961345'},
 {'1. open': '522.2900',
  '2. high': '528.6400',
  '3. low': '520.0110',
  '4. close': '524.8000',
  '5. volume': '1141310'},
 {'1. open': '515.0000',
  '2. high': '526.6900',
  '3. low': '512.8700',
  '4. close': '521.4000',
  '5. volume': '1923901'},
 {'1. open': '505.0000',
  '2. high': '519.5900',
  '3. low': '501.4100',
  '4. close': '515.2000',
  '5. volume': '2580066'},
 {'1. open': '488.8400',
  '2. high': '501.7700',
  '3. low': '482.8600',
  '4. close': '501.2900',
  '5. volume': '2579132'},
 {'1. open': '475.0000',
  '2. high': '476.1300',
  '3. low': '472.8500',
  '4. close': '474.5900',
  '5. volume': '881562'},
 {'1. open': '479.5400',
  '2. high': '479.5400',
  '3. low': '472.8143',
  '4. close': '474.9200',
  '5. volume': '889361'},
 {'1. open': '474.5000',
  '2. high': '480.8600',
  '3. low': '473.0150',
  '4. close': '476.0000',
  '5. volume': '981061'},
 {'1. open': '470.0000',
  '2. high': '476.7750',
  '3. low': '469.7045',
  '4. close': '476.0700',
  '5. volume': '1123060'},
 {'1. open': '463.7500',
  '2. high': '469.1900',
  '3. low': '463.7500',
  '4. close': '468.5800',
  '5. volume': '736547'},
 {'1. open': '466.7100',
  '2. high': '467.2500',
  '3. low': '462.7800',
  '4. close': '463.8800',
  '5. volume': '783092'},
 {'1. open': '462.3600',
  '2. high': '464.9000',
  '3. low': '459.5300',
  '4. close': '463.7300',
  '5. volume': '579436'},
 {'1. open': '459.9200',
  '2. high': '465.7700',
  '3. low': '456.1100',
  '4. close': '460.3800',
  '5. volume': '1132976'},
 {'1. open': '460.3700',
  '2. high': '461.3900',
  '3. low': '457.2500',
  '4. close': '461.0100',
  '5. volume': '655973'},
 {'1. open': '461.7000',
  '2. high': '462.6199',
  '3. low': '459.7600',
  '4. close': '460.3000',
  '5. volume': '537209'},
 {'1. open': '462.6800',
  '2. high': '464.5700',
  '3. low': '461.1200',
  '4. close': '461.7600',
  '5. volume': '447867'},
 {'1. open': '464.9800',
  '2. high': '465.0000',
  '3. low': '459.6900',
  '4. close': '462.1600',
  '5. volume': '631595'},
 {'1. open': '465.4900',
  '2. high': '466.4700',
  '3. low': '464.1298',
  '4. close': '466.0300',
  '5. volume': '313283'},
 {'1. open': '465.6000',
  '2. high': '466.6700',
  '3. low': '464.0201',
  '4. close': '465.7000',
  '5. volume': '502492'},
 {'1. open': '470.7700',
  '2. high': '471.6800',
  '3. low': '464.7600',
  '4. close': '466.4400',
  '5. volume': '562562'},
 {'1. open': '470.0500',
  '2. high': '471.7499',
  '3. low': '464.8700',
  '4. close': '467.1000',
  '5. volume': '3472549'},
 {'1. open': '468.8800',
  '2. high': '468.8800',
  '3. low': '465.3050',
  '4. close': '467.1300',
  '5. volume': '871215'},
 {'1. open': '467.0000',
  '2. high': '468.1000',
  '3. low': '463.7200',
  '4. close': '466.9900',
  '5. volume': '932061'},
 {'1. open': '470.8200',
  '2. high': '471.6200',
  '3. low': '466.6600',
  '4. close': '468.0700',
  '5. volume': '715816'},
 {'1. open': '468.9600',
  '2. high': '475.6900',
  '3. low': '467.8200',
  '4. close': '471.5100',
  '5. volume': '1031607'},
 {'1. open': '467.1500',
  '2. high': '469.8000',
  '3. low': '463.6500',
  '4. close': '467.6000',
  '5. volume': '3365244'},
 {'1. open': '460.0000',
  '2. high': '467.4899',
  '3. low': '459.1600',
  '4. close': '466.3400',
  '5. volume': '1041412'},
 {'1. open': '459.8000',
  '2. high': '460.7000',
  '3. low': '457.3900',
  '4. close': '460.0000',
  '5. volume': '658084'},
 {'1. open': '457.7500',
  '2. high': '459.1900',
  '3. low': '456.3050',
  '4. close': '459.0100',
  '5. volume': '669784'},
 {'1. open': '456.5000',
  '2. high': '458.5600',
  '3. low': '454.4400',
  '4. close': '458.3400',
  '5. volume': '702880'},
 {'1. open': '458.6400',
  '2. high': '459.7500',
  '3. low': '456.0100',
  '4. close': '458.5600',
  '5. volume': '742025'},
 {'1. open': '462.3000',
  '2. high': '463.2300',
  '3. low': '457.6650',
  '4. close': '459.1100',
  '5. volume': '1026596'},
 {'1. open': '465.6800',
  '2. high': '466.5834',
  '3. low': '462.5750',
  '4. close': '462.8000',
  '5. volume': '908416'},
 {'1. open': '470.7500',
  '2. high': '470.7500',
  '3. low': '465.7550',
  '4. close': '467.4600',
  '5. volume': '900460'},
 {'1. open': '468.8100',
  '2. high': '475.2900',
  '3. low': '468.6200',
  '4. close': '470.1300',
  '5. volume': '1042800'},
 {'1. open': '465.2300',
  '2. high': '469.7900',
  '3. low': '464.3500',
  '4. close': '468.6200',
  '5. volume': '768313'},
 {'1. open': '468.4200',
  '2. high': '468.8500',
  '3. low': '463.6180',
  '4. close': '465.2300',
  '5. volume': '915412'},
 {'1. open': '467.5100',
  '2. high': '470.1600',
  '3. low': '466.1600',
  '4. close': '468.8900',
  '5. volume': '845778'},
 {'1. open': '466.0000',
  '2. high': '470.5200',
  '3. low': '465.0100',
  '4. close': '467.6000',
  '5. volume': '990132'},
 {'1. open': '460.9000',
  '2. high': '470.3600',
  '3. low': '459.4900',
  '4. close': '470.3400',
  '5. volume': '1651560'},
 {'1. open': '455.0000',
  '2. high': '462.9400',
  '3. low': '455.0000',
  '4. close': '460.9400',
  '5. volume': '1173703'},
 {'1. open': '455.9800',
  '2. high': '456.0000',
  '3. low': '451.8000',
  '4. close': '452.7200',
  '5. volume': '1267964'},
 {'1. open': '465.6100',
  '2. high': '466.0000',
  '3. low': '457.2500',
  '4. close': '458.4800',
  '5. volume': '1150758'},
 {'1. open': '467.6700',
  '2. high': '468.6600',
  '3. low': '465.4700',
  '4. close': '467.3500',
  '5. volume': '513802'},
 {'1. open': '468.0900',
  '2. high': '469.6800',
  '3. low': '466.2300',
  '4. close': '467.0800',
  '5. volume': '866955'},
 {'1. open': '467.4700',
  '2. high': '469.9000',
  '3. low': '466.7800',
  '4. close': '469.7100',
  '5. volume': '548809'},
 {'1. open': '468.0000',
  '2. high': '469.1200',
  '3. low': '466.8400',
  '4. close': '468.3100',
  '5. volume': '558976'},
 {'1. open': '467.7700',
  '2. high': '468.7700',
  '3. low': '464.9200',
  '4. close': '467.0800',
  '5. volume': '735291'},
 {'1. open': '465.8400',
  '2. high': '467.0000',
  '3. low': '463.1500',
  '4. close': '466.2000',
  '5. volume': '677219'},
 {'1. open': '463.6000',
  '2. high': '468.3200',
  '3. low': '453.0000',
  '4. close': '464.8300',
  '5. volume': '1130786'},
 {'1. open': '466.2800',
  '2. high': '467.4000',
  '3. low': '463.5100',
  '4. close': '464.0800',
  '5. volume': '804062'},
 {'1. open': '471.1100',
  '2. high': '471.1100',
  '3. low': '466.8000',
  '4. close': '467.1800',
  '5. volume': '565691'},
 {'1. open': '469.8800',
  '2. high': '472.3450',
  '3. low': '469.5000',
  '4. close': '470.5600',
  '5. volume': '634358'},
 {'1. open': '469.0000',
  '2. high': '470.6200',
  '3. low': '467.9750',
  '4. close': '468.8800',
  '5. volume': '482564'},
 {'1. open': '466.0800',
  '2. high': '468.7600',
  '3. low': '465.2101',
  '4. close': '468.3900',
  '5. volume': '595046'},
 {'1. open': '467.5000',
  '2. high': '468.0000',
  '3. low': '463.7800',
  '4. close': '466.1600',
  '5. volume': '599051'},
 {'1. open': '464.0000',
  '2. high': '466.8100',
  '3. low': '463.1600',
  '4. close': '466.6800',
  '5. volume': '723436'},
 {'1. open': '463.1600',
  '2. high': '463.4999',
  '3. low': '460.1800',
  '4. close': '462.7800',
  '5. volume': '796391'}]

In [58]:
import snowflake.connector
from google.colab import userdata

# Fetch Snowflake credentials from Colab secrets
user = userdata.get('SNOWFLAKE_USER')
password = userdata.get('SNOWFLAKE_PASSWORD')
account = userdata.get('SNOWFLAKE_ACCOUNT')
warehouse = userdata.get('SNOWFLAKE_WAREHOUSE')
database = userdata.get('SNOWFLAKE_DATABASE')
schema = userdata.get('SNOWFLAKE_SCHEMA')

# Set up your Snowflake connection parameters
conn = snowflake.connector.connect(
    user=user,
    password=password,
    account=account,
    warehouse=warehouse,
    database=database,
    schema=schema
)

# Create a cursor object
cur = conn.cursor()

# SQL command to create the table with a primary key
create_table_query = """
CREATE OR REPLACE TABLE stock_prices (
    date DATE NOT NULL,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    volume INTEGER,
    symbol STRING,
    PRIMARY KEY (date, symbol)
);
"""

# Execute the command
cur.execute(create_table_query)

# Close the cursor and connection
cur.close()
conn.close()

In [59]:
import snowflake.connector
from google.colab import userdata
import requests

def return_last_90d_price(symbol):
    """
    - return the last 90 days of the stock prices of symbol as a list of json strings
    """
    vantage_api_key = userdata.get('vantage_api_key')
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={vantage_api_key}'
    r = requests.get(url)
    data = r.json()
    results = []  # empty list to hold the 90 days of stock info (open, high, low, close, volume)
    for d in data["Time Series (Daily)"]:  # d is a date: "YYYY-MM-DD"
        daily_data = data["Time Series (Daily)"][d]
        # Create a record to insert into the database
        record = (
            d,  # date
            float(daily_data['1. open']),
            float(daily_data['2. high']),
            float(daily_data['3. low']),
            float(daily_data['4. close']),
            int(daily_data['5. volume']),
            symbol
        )
        results.append(record)
    return results

# Use the function to get the last 90 days of stock prices for a specific symbol
symbol = "LMT"
prices = return_last_90d_price(symbol)

# Set up your Snowflake connection parameters using secrets
conn = snowflake.connector.connect(
    user=userdata.get('SNOWFLAKE_USER'),
    password=userdata.get('SNOWFLAKE_PASSWORD'),
    account=userdata.get('SNOWFLAKE_ACCOUNT'),
    warehouse=userdata.get('SNOWFLAKE_WAREHOUSE'),
    database=userdata.get('SNOWFLAKE_DATABASE'),
    schema=userdata.get('SNOWFLAKE_SCHEMA')
)

# Create a cursor object
cur = conn.cursor()

# Insert records into the table
insert_query = """
INSERT INTO stock_prices (date, open, high, low, close, volume, symbol)
VALUES (%s, %s, %s, %s, %s, %s, %s);
"""

# Execute the insert statement for each price record
for price in prices:
    cur.execute(insert_query, price)

# Commit the transaction
conn.commit()

# Close the cursor and connection
cur.close()
conn.close()

In [61]:
import snowflake.connector
from google.colab import userdata
import requests

def return_last_90d_price(symbol):
    """
    - return the last 90 days of the stock prices of symbol as a list of tuples
    """
    vantage_api_key = userdata.get('vantage_api_key')
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={vantage_api_key}'
    r = requests.get(url)
    data = r.json()
    results = []  # empty list to hold the 90 days of stock info (open, high, low, close, volume)
    for d in data["Time Series (Daily)"]:  # d is a date: "YYYY-MM-DD"
        daily_data = data["Time Series (Daily)"][d]
        # Create a record to insert into the database
        record = (
            d,  # date
            float(daily_data['1. open']),
            float(daily_data['2. high']),
            float(daily_data['3. low']),
            float(daily_data['4. close']),
            int(daily_data['5. volume']),
            symbol
        )
        results.append(record)
    return results

def get_record_count(cur):
    """
    Get the count of records in the stock_prices table
    """
    cur.execute("SELECT COUNT(*) FROM stock_prices;")
    return cur.fetchone()[0]

# Use the function to get the last 90 days of stock prices for a specific symbol
symbol = "LMT"
prices = return_last_90d_price(symbol)

# Set up your Snowflake connection parameters using secrets
conn = snowflake.connector.connect(
    user=userdata.get('SNOWFLAKE_USER'),
    password=userdata.get('SNOWFLAKE_PASSWORD'),
    account=userdata.get('SNOWFLAKE_ACCOUNT'),
    warehouse=userdata.get('SNOWFLAKE_WAREHOUSE'),
    database=userdata.get('SNOWFLAKE_DATABASE'),
    schema=userdata.get('SNOWFLAKE_SCHEMA')
)


cur = conn.cursor()

initial_count = get_record_count(cur)
print(f"Initial record count: {initial_count}")

merge_query = """
MERGE INTO stock_prices AS target
USING (SELECT %s AS date, %s AS open, %s AS high, %s AS low, %s AS close, %s AS volume, %s AS symbol) AS source
ON target.date = source.date AND target.symbol = source.symbol
WHEN NOT MATCHED THEN
    INSERT (date, open, high, low, close, volume, symbol)
    VALUES (source.date, source.open, source.high, source.low, source.close, source.volume, source.symbol);
"""

for price in prices:
    cur.execute(merge_query, price)

conn.commit()

first_insertion_count = get_record_count(cur)
print(f"Record count after first insertion: {first_insertion_count}")

for price in prices:
    cur.execute(merge_query, price)

conn.commit()

second_insertion_count = get_record_count(cur)
print(f"Record count after second insertion: {second_insertion_count}")

cur.close()
conn.close()

Initial record count: 100
Record count after first insertion: 100
Record count after second insertion: 100